import { useState, useEffect } from "react";
import Head from "next/head";
import Link from "next/link";
import { API, Storage } from "aws-amplify";
import { Container, Heading, Box } from "@chakra-ui/react";
import { listPosts } from "../src/graphql/queries";
import PostText from "../components/FrontPage/PostText";
import PostImage from "../components/FrontPage/PostImage";

export default function Home() {
  const [posts, setPosts] = useState([]);
  useEffect(() => {
    fetchPosts();
  }, []);
  async function fetchPosts() {
    const postData = await API.graphql({
      query: listPosts,
    });
    const { items } = postData.data.listPosts;
    // Fetch images from S3 for posts that contain a cover image
    const postsWithImages = await Promise.all(
      items.map(async (post) => {
        if (post.postImage) {
          post.postImage = await Storage.get(post.postImage);
        }
        return post;
      })
    );
    setPosts(postsWithImages);
  }
  return (
    <div>
      <Head>
        <title>Big D TBD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="7xl" p={12}>
        <Heading as="h1">Stories by Danno</Heading>
        {posts.map((post, index) => {
          return (
            <Link key={index} href={`/posts/${post.id}`} passHref>
              <Box
                mt={{ base: "1", sm: "5" }}
                display="flex"
                flexDir={{ base: "column", sm: "row" }}
                justifyContent="space-between"
              >
                <PostImage postEmoji={post.postEmoji} />
                <PostText post={post} />
              </Box>
            </Link>
          );
        })}
      </Container>

      <footer>
        <span></span>
      </footer>
    </div>
  );
}
