import { useState, useEffect } from "react";
import Head from "next/head";
import { API, graphqlOperation } from "aws-amplify";
import { postsByDate } from "../src/graphql/queries";
import PostItem from "../components/FrontPage/PostItem";

export default function Home() {
  const [posts, setPosts] = useState([]);
  useEffect(() => {
    fetchPosts();
  }, []);
  async function fetchPosts() {
    const postData = await API.graphql(
      graphqlOperation(postsByDate, {
        type: "post",
        sortDirection: "DESC",
        limit: 10,
      })
    );
    const { items } = postData.data.postsByDate;
    setPosts(items);
  }
  return (
    <>
      <Head>
        <title>Milk</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1 className="text-3xl font-semibold tracking-wide mt-6 dark:text-white">
        The Good Stuff
      </h1>
      <section className="text-gray-600 body-font overflow-hidden">
        <div className="divide-y divide-gray-200 dark:divide-gray-700">
          {posts.map((post, index) => (
            <PostItem key={index} post={post} />
          ))}
        </div>
      </section>

      <footer>
        <span></span>
      </footer>
    </>
  );
}
